version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/filesystem
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/console
    versions:
    - 4.4.19
    - 4.4.20
  - dependency-name: symfony/http-foundation
    versions:
    - 4.4.19
  - dependency-name: phpunit/phpunit
    versions:
    - 8.5.14
